### ISSUE TITLE
Error when using allow_any_instance_of

### ISSUE THREAD

**Issue by fabioperrella** [rranelli/advisor#4]
Given a method that is being listened by `log_calls_to`, example:

```ruby
class NextLogin
  extend Advisor::Loggable
  log_calls_to :execute, result: true
```

When using `allow_any_instance_of`, rspec raises a error:

```ruby
allow_any_instance_of(
  NextLogin
).to receive(:execute).and_return('lala')
```

```ruby
Failure/Error: allow_any_instance_of(
       Using `any_instance` to stub a method (execute) that has been defined on a prepended module (Advisor::Advices::CallLogger(execute)) is not supported.
```

**Comment by rranelli** [comment]
Well, if rspec refuses to stub prepended methods, there is nothing that can be done here. 

In order to simulate the `around filter`, Advisor actually defines the advised method in an anonymous module that is prepended to the advised class.

Is it possible to stub your class constructor to return a double with the desired return value for `#execute` ?

**Comment by fabioperrella** [comment]
Yes it is!

Maybe you could add this "warning" to the REAME.
